/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and capability probe
         * @description Liveness/capability probe. Reports which optional integrations are configured
         *     so a reviewer running with only a database can see what's degraded and why.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guardrails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The calling window and retry policy every published agent uses
         * @description One fixed, org-wide policy (app/services/guardrails.py) — sent explicitly on every publish rather than left to Hunar's org defaults, precisely so it can be read back here instead of being opaque.
         */
        get: operations["get_guardrails_guardrails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /**
         * Create a job
         * @description Stores the raw job description. Nothing is compiled yet — PUT /jobs/{id}/requirements does that.
         */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a job's requirements
         * @description Recompiles the raw JD and creates a new draft AgentVersion (origin=COMPILED, unpublished) for every language the compiled JD implies. Never edits an existing version — versions are immutable (CLAUDE.md).
         */
        put: operations["update_requirements_jobs__job_id__requirements_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version history with composite score per version */
        get: operations["list_versions_jobs__job_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/versions/{version_no}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a draft version to Hunar
         * @description `language` disambiguates: versions are numbered per (job, language), so version_no alone is not unique across languages.
         */
        post: operations["publish_job_version_jobs__job_id__versions__version_no__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The six rehearsal personas */
        get: operations["list_personas_jobs__job_id__personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Source candidates
         * @description Every field falls back to the job's own compiled search_query when omitted, so re-sourcing more of the same needs no body at all.
         */
        post: operations["source_candidates_jobs__job_id__source_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List candidates, best match first */
        get: operations["list_candidates_jobs__job_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Launch outbound screening calls
         * @description Blocked candidates are returned WITH reasons, never silently skipped — the consent/DNC guard is unbypassable (CLAUDE.md).
         */
        post: operations["launch_calls_jobs__job_id__call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The live candidate/call board
         * @description Refreshes non-terminal outreach rows on read (polling), then reads whatever state is current — the board is correct even if Hunar's webhooks never arrive.
         */
        get: operations["get_board_jobs__job_id__board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export candidates as CSV
         * @description One row per candidate, one column per screening question id plus the four standard result fields, pulled from each candidate's latest call result.
         */
        get: operations["export_candidates_jobs__job_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One agent version's full built prompt and result schema */
        get: operations["get_version_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{version_id}/rehearse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rehearse an agent version
         * @description Runs all six personas against this version and scores the result. Returns immediately with a run id in PENDING status; poll GET /runs/{id} for progress.
         */
        post: operations["rehearse_version_versions__version_id__rehearse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{version_id}/latest-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This version's most recent rehearsal run, if it has one
         * @description null if the version has never been rehearsed — a valid state, not an error, so this returns 200 rather than 404.
         */
        get: operations["get_latest_run_versions__version_id__latest_run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A rehearsal run's status, scores, and per-case summaries */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One persona's full transcript, extraction, ground truth, metrics and failures */
        get: operations["get_case_runs__run_id__cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose a prompt patch addressing this run's worst failures */
        post: operations["propose_run_patch_runs__run_id__patch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patches/{patch_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a proposed patch
         * @description Creates AgentVersion n+1 (origin=PATCHED) from the patch's prompt, then immediately rehearses it against the same personas as the parent run — a patch's effect is measured, never assumed.
         */
        post: operations["accept_run_patch_patches__patch_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a candidate's phone, language, or DNC flag
         * @description A plain field edit — unlike POST .../consent, this never sets consent_recorded_at. The outbound-call guard still checks consent independently at call time regardless of what phone_e164 is set to here.
         */
        patch: operations["patch_candidate_candidates__candidate_id__patch"];
        trace?: never;
    };
    "/candidates/{candidate_id}/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record consent
         * @description Sets phone_e164 and consent_recorded_at together — the only route that does, per CLAUDE.md's rule that a call needs an explicitly consented number.
         */
        post: operations["record_candidate_consent_candidates__candidate_id__consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/hunar/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a Hunar call-lifecycle webhook
         * @description `kind` is one of status|recording|result|summary. The signature is verified over the RAW request body (see app/integrations/hunar/signature.py); an invalid signature returns 401 and is never applied. An unrecognised call/request id is still accepted (200) and logged rather than erroring, since Hunar would otherwise retry a payload it has no way to fix. `X-Hunar-Signature` is this project's assumed header name for the signature — CLAUDE.md documents the HMAC computation itself but not the header carrying it.
         */
        post: operations["receive_hunar_webhook_webhooks_hunar__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent raw webhook events, valid or not
         * @description The append-only log every inbound Hunar webhook is recorded to, regardless of whether its signature verified or it resolved to a known call — see WebhookEvent's docstring. Diagnostic only.
         */
        get: operations["list_webhook_events_debug_webhooks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentVersionOrigin
         * @enum {string}
         */
        AgentVersionOrigin: "COMPILED" | "PATCHED";
        /**
         * AgentVersionRead
         * @description GET /versions/{id} — the version's full built prompt/schema, not just its identity
         *     (VersionSummary/VersionHistoryRow carry only the latter). Needed wherever a screen must
         *     show or diff against the exact text that was built for this version, e.g. the rehearsal
         *     screen's patch DiffView, which diffs the current agent_prompt against a proposed one.
         */
        AgentVersionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Version No */
            version_no: number;
            language: components["schemas"]["Language"];
            origin: components["schemas"]["AgentVersionOrigin"];
            voice_persona: components["schemas"]["VoicePersona"];
            /** Persona Name */
            persona_name: string;
            /** Agent Prompt */
            agent_prompt: string;
            /** Objective */
            objective: string;
            /** Introduction */
            introduction: string;
            /** Result Prompt */
            result_prompt: string;
            /** Result Schema */
            result_schema: {
                [key: string]: unknown;
            };
            /** Hunar Agent Id */
            hunar_agent_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * BlockedCandidate
         * @description One candidate call_candidates refused to dial, and why. Recruiters must see this list —
         *     per CLAUDE.md the guard is unbypassable, so a skip is never silent.
         */
        BlockedCandidate: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Reason */
            reason: string;
        };
        /** BoardResponse */
        BoardResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Rows */
            rows: components["schemas"]["BoardRow"][];
        };
        /**
         * BoardRow
         * @description One candidate plus their latest outreach attempt, if any. Fields from Outreach are None
         *     when the candidate has never been called.
         */
        BoardRow: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Full Name */
            full_name: string;
            /** Match Score */
            match_score: number | null;
            /** Phone E164 */
            phone_e164: string | null;
            /** Consent Recorded At */
            consent_recorded_at: string | null;
            /** Dnc */
            dnc: boolean;
            /** Outreach Id */
            outreach_id: string | null;
            /** Agent Version Id */
            agent_version_id: string | null;
            /** Status */
            status: string | null;
            /** Lifecycle Status */
            lifecycle_status: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Recording Url */
            recording_url: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Call Summary */
            call_summary: string | null;
            /** Is Simulated */
            is_simulated: boolean;
        };
        /** CallLaunchSummary */
        CallLaunchSummary: {
            /** Queued */
            queued: components["schemas"]["QueuedCall"][];
            /** Blocked */
            blocked: components["schemas"]["BlockedCandidate"][];
            /** Versions Used */
            versions_used: {
                [key: string]: string;
            };
            /** Estimated Minutes */
            estimated_minutes: number;
        };
        /** CallRequest */
        CallRequest: {
            /** Candidate Ids */
            candidate_ids: string[];
        };
        /**
         * CandidatePatch
         * @description PATCH /candidates/{id} — phone, language, dnc, per the API surface. Every field is
         *     optional; only what is provided is changed.
         */
        CandidatePatch: {
            /** Phone E164 */
            phone_e164?: string | null;
            preferred_language?: components["schemas"]["Language"] | null;
            /** Dnc */
            dnc?: boolean | null;
        };
        /** CandidateRead */
        CandidateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Source Provider */
            source_provider: string;
            /** Source Ref */
            source_ref: string;
            /** Full Name */
            full_name: string;
            /** Headline */
            headline: string | null;
            /** Current Title */
            current_title: string | null;
            /** Current Company */
            current_company: string | null;
            /** Location */
            location: string | null;
            /** Skills */
            skills: unknown[];
            /** Years Experience */
            years_experience: number | null;
            /** Linkedin Url */
            linkedin_url: string | null;
            /** Phone E164 */
            phone_e164: string | null;
            preferred_language: components["schemas"]["Language"] | null;
            /** Match Score */
            match_score: number | null;
            /** Match Breakdown */
            match_breakdown: {
                [key: string]: unknown;
            } | null;
            /** Consent Recorded At */
            consent_recorded_at: string | null;
            /** Consent Channel */
            consent_channel: string | null;
            /** Dnc */
            dnc: boolean;
        };
        /** CaseRead */
        CaseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Persona Id
             * Format: uuid
             */
            persona_id: string;
            /** Archetype */
            archetype: string;
            /** Transcript */
            transcript: unknown[] | null;
            /** Extracted Result */
            extracted_result: {
                [key: string]: unknown;
            } | null;
            /** Ground Truth */
            ground_truth: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            } | null;
            /** Failures */
            failures: unknown[] | null;
        };
        /**
         * CaseSummary
         * @description One row of RunRead.case_summaries — enough to pick a case to drill into, not the full
         *     transcript (see GET /runs/{id}/cases/{case_id} for that).
         */
        CaseSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Persona Id
             * Format: uuid
             */
            persona_id: string;
            /** Archetype */
            archetype: string;
            /** Turn Count */
            turn_count: number | null;
            /** Estimated Seconds */
            estimated_seconds: number | null;
        };
        /** ConsentCreate */
        ConsentCreate: {
            /** Phone E164 */
            phone_e164: string;
            /**
             * Channel
             * @default MANUAL
             */
            channel: string;
        };
        /** GuardrailsRead */
        GuardrailsRead: {
            /** Allowed Days */
            allowed_days: ("MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY")[];
            /** Earliest Call Time */
            earliest_call_time: string;
            /** Last Call Time */
            last_call_time: string;
            /** Timezone */
            timezone: string;
            /** Max Retry Count */
            max_retry_count: number;
            /**
             * Retry Interval Hours
             * @enum {integer}
             */
            retry_interval_hours: 0 | 3 | 6 | 9 | 12 | 24;
            /** Inside Window Now */
            inside_window_now: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreate */
        JobCreate: {
            /** Title */
            title: string;
            /** Raw Jd */
            raw_jd: string;
        };
        /** JobRead */
        JobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Raw Jd */
            raw_jd: string;
            /** Compiled */
            compiled: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Language
         * @description Belongs to the agent, not the call — see CLAUDE.md.
         * @enum {string}
         */
        Language: "ENGLISH" | "HINDI" | "TAMIL" | "TELUGU" | "KANNADA" | "MARATHI" | "MALAYALAM" | "GUJARATI" | "BENGALI" | "TURKISH" | "ARABIC" | "SPANISH";
        /** PatchAcceptResponse */
        PatchAcceptResponse: {
            version: components["schemas"]["VersionSummary"];
            run: components["schemas"]["RunRead"];
            /** Score Delta */
            score_delta: {
                [key: string]: number;
            };
        };
        /** PatchRead */
        PatchRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Proposed Agent Prompt */
            proposed_agent_prompt: string;
            /** Rationale */
            rationale: unknown[];
            /** Accepted */
            accepted: boolean;
            /** Resulting Version Id */
            resulting_version_id: string | null;
        };
        /** PersonaRead */
        PersonaRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Archetype */
            archetype: string;
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /** Ground Truth */
            ground_truth: {
                [key: string]: unknown;
            };
            /** Behaviour */
            behaviour: {
                [key: string]: unknown;
            };
        };
        /** QueuedCall */
        QueuedCall: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /**
             * Outreach Id
             * Format: uuid
             */
            outreach_id: string;
            /** Request Id */
            request_id: string;
            /** Hunar Call Id */
            hunar_call_id: string;
        };
        /** RehearseAccepted */
        RehearseAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
        };
        /**
         * RequirementsUpdate
         * @description Body for PUT /jobs/{id}/requirements — a revised raw JD. Recompiling always creates new
         *     draft AgentVersion row(s); it never edits an existing one (CLAUDE.md: versions immutable).
         */
        RequirementsUpdate: {
            /** Raw Jd */
            raw_jd: string;
        };
        /** RequirementsUpdateResponse */
        RequirementsUpdateResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /** RunRead */
        RunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Agent Version Id
             * Format: uuid
             */
            agent_version_id: string;
            /** Status */
            status: string;
            /** Scores */
            scores: {
                [key: string]: unknown;
            } | null;
            /** Llm Calls */
            llm_calls: number;
            /** Cached Calls */
            cached_calls: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
            /** Case Summaries */
            case_summaries: components["schemas"]["CaseSummary"][];
        };
        /**
         * SourceRequest
         * @description Body for POST /jobs/{id}/source. Every field optional — omitted fields fall back to the
         *     job's own compiled search_query, so 'source more like this' needs no body at all.
         */
        SourceRequest: {
            /** Titles */
            titles?: string[] | null;
            /** Skills */
            skills?: string[] | null;
            /** Locations */
            locations?: string[] | null;
            /** Min Years */
            min_years?: number | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** SourceResponse */
        SourceResponse: {
            /** Provider */
            provider: string;
            /** Cached */
            cached: boolean;
            /** Candidates */
            candidates: components["schemas"]["CandidateRead"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VersionHistoryRow
         * @description One row of GET /jobs/{id}/versions: a version plus its most recent rehearsal composite,
         *     if it has been rehearsed at all.
         */
        VersionHistoryRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version No */
            version_no: number;
            language: components["schemas"]["Language"];
            origin: components["schemas"]["AgentVersionOrigin"];
            /** Hunar Agent Id */
            hunar_agent_id: string | null;
            /** Latest Composite Score */
            latest_composite_score: number | null;
        };
        /** VersionSummary */
        VersionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Version No */
            version_no: number;
            language: components["schemas"]["Language"];
            origin: components["schemas"]["AgentVersionOrigin"];
            /** Hunar Agent Id */
            hunar_agent_id: string | null;
        };
        /**
         * VoicePersona
         * @enum {string}
         */
        VoicePersona: "NEHA" | "ROY" | "ZOE" | "SAM" | "MIRA" | "EESHA";
        /** WebhookEventRead */
        WebhookEventRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Event Type */
            event_type: string;
            /** Call Id */
            call_id: string | null;
            /** Request Id */
            request_id: string | null;
            /** Signature Valid */
            signature_valid: boolean;
            /** Raw Payload */
            raw_payload: {
                [key: string]: unknown;
            };
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_guardrails_guardrails_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailsRead"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"][];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_requirements_jobs__job_id__requirements_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementsUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_jobs__job_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionHistoryRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_job_version_jobs__job_id__versions__version_no__publish_post: {
        parameters: {
            query: {
                language: components["schemas"]["Language"];
            };
            header?: never;
            path: {
                job_id: string;
                version_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personas_jobs__job_id__personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_candidates_jobs__job_id__source_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_jobs__job_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_calls_jobs__job_id__call_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallLaunchSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_jobs__job_id__board_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_candidates_jobs__job_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rehearse_version_versions__version_id__rehearse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RehearseAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_run_versions__version_id__latest_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_runs__run_id__cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_run_patch_runs__run_id__patch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_run_patch_patches__patch_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchAcceptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_candidate_candidates__candidate_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidatePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_candidate_consent_candidates__candidate_id__consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_hunar_webhook_webhooks_hunar__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "status" | "recording" | "result" | "summary";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_webhook_events_debug_webhooks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
