"""add outreach call_summary

Revision ID: 86abffcc0b45
Revises: e5494f4bf0ad
Create Date: 2026-08-25 12:30:23.488174

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "86abffcc0b45"
down_revision: str | None = "e5494f4bf0ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outreach", sa.Column("call_summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outreach", "call_summary")
    # ### end Alembic commands ###
